### ISSUE TITLE
Supreme Dark Sorceress has Dreadlord starting traits

### ISSUE THREAD

**Issue by chadvandy** [chadvandy/community_bugfix_mod#16]
Report says "I read somewhere", no need to investigate this too urgently

**Comment by sm0kin** [comment]
> wh2_main_skill_innate_all_strategist
wh2_main_skill_innate_all_strong,
wh2_main_skill_innate_all_tactician
wh2_main_skill_innate_def_spiteful

should be replaced by:
>wh2_main_skill_innate_all_intelligent
wh2_main_skill_innate_all_knowledgeable
