### ISSUE TITLE
CBFM causes Hinder Replenishment to reduce replenishment of embedded lord

### ISSUE THREAD

**Issue by chadvandy** [chadvandy/community_bugfix_mod#17]
> I asked this before so I'm sorry to repeat it but why does this cause the hinder replenishment hero ability to reduce the replenishment of the embedded lord? Is it actually intended to be that way? If so that's a large debuff for a niche skill.

Not sure exactly what this is means tbh

**Comment by chadvandy** [comment]
@sm0kin

**Comment by sm0kin** [comment]
The effect text is redundant. But Jianni and I used the opportunity to test the fix and turns out it doesn't work anymore.

https://trello.com/c/LWqBQayV/465-hinder-replenishment-doesnt-work-on-chaos-horde-replenishment

**Comment by chadvandy** [comment]
Added that trello pack onto my branch
