### ISSUE TITLE
Empire dilemmas show same button text

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/community_bugfix_mod#20]
The effects are stil different though

**Comment by sm0kin** [comment]
https://i.redd.it/xw3c6hqij8351.jpg

**Comment by sm0kin** [comment]
![civilwar_bug](https://user-images.githubusercontent.com/42816583/85015936-22197e80-b169-11ea-865b-649aa77b15f3.png)

can be reproduced.

**Comment by Harmandodelavega** [comment]
https://i.ibb.co/hmW3MRJ/Sin-t-tulo.png
