### ISSUE TITLE
Orc Boy Scrap Shield Upgrade works regardless of LD drops

### ISSUE THREAD

**Issue by chadvandy** [chadvandy/community_bugfix_mod#21]
> Hi guys, the new orc boy scrap shield upgrade seems to keep working no matter how low their leadership drops.
I've tested it with wavering and shattered orc boyz and both show the shield to be still effect on the unit info card.
Thanks for all the hard work by the way.

**Comment by sm0kin** [comment]
Tested the padded shield upgrade and can confirm the report.
I think all those upgrades should use the special_ability_to_auto_deactivate_flags table
> wh2_dlc15_unit_passive_heavy_ammo	morale_is_wavering_or_lower
wh2_dlc15_unit_passive_nightgoblin_poison	morale_is_wavering_or_lower
wh2_dlc15_unit_passive_padded_shield	morale_is_wavering_or_lower
wh2_dlc15_unit_passive_sorcery_weapon	morale_is_wavering_or_lower

**Comment by sm0kin** [comment]
On second thought, linking the scrap update with a new ability with a correct flag would be a cleaner solution.

**Comment by sm0kin** [comment]
https://github.com/chadvandy/community_bugfix_mod/commit/3721e462d7950d8ce1187632370db2c7031dd2df
