### ISSUE TITLE
TK dismemberment issue again

### ISSUE THREAD

**Issue by chadvandy** [chadvandy/community_bugfix_mod#22]
> Tomb Kings are not dismembering. I know there is a mod that is supposed to fix that, but it isn't updated.
And thanks for your replies on the treb issue as well as your dedication with this project. It means so much.

**Comment by sm0kin** [comment]
tl;dr
A army of dismembered unit models looks stupid. Therefore no dismemberment for factions with resurrection mechanics. The exception are chaff units like zombies.


From the recent "The Total WAAAGH! Update" patchnotes:
> - Depth Guard will no longer dismember

From the C&C discord:

> Norse, Devilish Picaroon19/05/2019
> Didn't CA disable dismemberment on most undead.
> So they'd stop running around in pieces
> 
> Cataph19/05/2019
> apparently not
> it's a problem with having dismember stuff with Nehek though, I assume
> 
> Norse, Devilish Picaroon19/05/2019
> Yeah, most undead factions are not allowed to dismember.
> 
> Cataph19/05/2019
> derp guard correctly has -1 in both alive columns
> 
> Norse, Devilish Picaroon19/05/2019
> Because they have easy access to resurrect.
> 
> Cataph19/05/2019
> there's a whole bunch of stuff to fix then
> bog standard zombies can still dismember
> 
> Norse, Devilish Picaroon19/05/2019
> Yeah, I think they only kept it for specific chaffy undead.
> They nixxed it on tomb kings for example.
> Prolly because of their faction mechanic in battle.
> Which would lead to hordes of skeleton legs.
