### ISSUE TITLE
Blessed Trebuchet gives direct friendly fire, though stating it won't

### ISSUE THREAD

**Issue by chadvandy** [chadvandy/community_bugfix_mod#23]

**Comment by Harmandodelavega** [comment]
devs mentioned only the explosion won't cause friendly fire, just loc change

**Comment by sm0kin** [comment]
The unit bullet point tooltip says:
"These blessed munitions would never harm the righteous! Friendly units caught in their explosions suffer no damage!"

...Although the blessing won't protect you from a direct hit.
...Though the blessing won't protect you were you to be directly hit by a giant stone.
...Though the blessing can't protect friendly units from direct hits.

**Comment by sm0kin** [comment]
https://trello.com/c/9PTiVMzd/678-blessed-trebuchet-gives-friendly-fire-though-stating-it-wont
