### ISSUE TITLE
No option to resurrect Golden Order when capturing Pfeildorf as Reikland

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/community_bugfix_mod#26]
You can return certain regions to an elector even if they are dead, effectively resurrecting them except you can't return region to the Golden Order and maybe not even for Reikland

**Comment by sm0kin** [comment]
Confirmed for reikland (also other elector count factions like wissenland) trying to reinstate the golden order. Works the other way around though - the golden order can reinstate reikland.
