### ISSUE TITLE
Black Ark Admirals have a immortal hero innate skill and the level 20 lord immortal skill

### ISSUE THREAD

**Issue by sm0kin** [chadvandy/community_bugfix_mod#27]
Bug: Black Ark Admirals have a immortal hero innate skill and the level 20 lord immortal skill.
Seems to be a remnant from the time before the "Potion of Speed" update. The Admiral had no skill tree back then.

Solution 1: set the immortality effect of the innate skill to 0
Solution 2: remove the level 20 lord immortal skill by setting its skill node to invisible

What's your opinion?

**Comment by Harmandodelavega** [comment]
I think you know better but why not make him spawn with immortality already skilled, would help with people not knowing if Black arks respawn
