### ISSUE TITLE
Spirit of the Jungle armies and their opponents both gain enough experience to go from 0 to 9 after a battle

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/community_bugfix_mod#29]
should be easily replicable in any spirit of the jungle campaign

**Comment by sm0kin** [comment]
Couldn't reproduce. Tried ME, Vortex, manuell battle, autoresolve, siege and land battle. I'd call "no bug".

**Comment by Harmandodelavega** [comment]
Had it on 2 different Nakai campaigns plus saw it on forums, there's something going on

**Comment by sm0kin** [comment]
I can think of two possible ways you'd get +9 after a single battle:
1: In script: all units that participate in the final (vortex) battle become rank 9
2: A bug exists that doubles ranks gained by horde factions. I only observed this using the add_experience_to_units_commanded_by_character function but I think it's also bugged for effects.
So assuming there is a event or something that awards + 5 ranks (effect bundle), the ranks added gets double and your army ends up having rank 9 units.

**Comment by Harmandodelavega** [comment]
Was ME campaign, double the experience is not enough to go from 0 to 9, maybe it's some horde building, I'm stumped

**Comment by Harmandodelavega** [comment]
Maybe It's been fixed since Hunter and Beast but still broken in old campaigns

**Comment by sm0kin** [comment]
moved to trello
