### ISSUE TITLE
Norscan Lord has normal yellow line, not Chaos God

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/community_bugfix_mod#30]
I unfortunately shipped a fix that had a new normal yellow line for Norscan lords, better than the bugged one still, the problem is changing it again which I am not capable of anyways and the fact it will remove any skilled points.

The Beta fix simply changed the set linked to the lord so for live if you don't want to reset the whole skill tree you'd have to manually recreate the new Chaos god yellow line

**Comment by sm0kin** [comment]
Copied your message to the related trello card.
