### ISSUE TITLE
Garrison assigned to Massif Orcal for WE and VC has been copy pasted 3 times

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/community_bugfix_mod#52]
https://forums.totalwar.com/discussion/267163/massif-orcal-garrisons-are-too-big-for-wood-elfves-and-vamps#latest

also related to this https://trello.com/c/Yv4lLOnz/619-wood-elves-massif-orcal-and-tor-yvresse-can-be-upgraded-to-tier-5-but-only-get-normal-outpost-buildings

**Comment by sm0kin** [comment]
As you already mentioned, both issues are closely related, we might as well merged them only keep the trello card.
