### ISSUE TITLE
Mistwalkers do not receive murderous mastery

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/community_bugfix_mod#55]
related to this https://trello.com/c/QFXzSBTZ/643-yvresse-mistwalkers-not-benefitting-from-many-buffs, should take a look at it

https://forums.totalwar.com/discussion/267432/mistwalkers-do-not-receive-murderous-mastery#latest

**Comment by sm0kin** [comment]
can be reproduced, definitely not working as intended
