### ISSUE TITLE
@BlobWarfare had a 200k deposit to his bank account out of nowhere pvp campaign, mods used: TTC & CBF

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/community_bugfix_mod#59]

**Comment by sm0kin** [comment]
tl;dr 
don't think we have to investigate further

Possible causes:
1: Indoctrinated a prisoner and its faction had 4 million coins laying around -> +200.000 income that don't show up in the treasury summary.

2: A mod (def not cbf) made changes to the wh2_dlc15_eltharion_lair script and increase the lair_income_stolen variable.

3: cm:treasury_mod(cm:get_local_faction(true), 200000)
Some script mod uses methods like this for test purposes and the author forgot to deactivate it:
