### ISSUE TITLE
Helf AI only recruits Archmages

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/community_bugfix_mod#63]

**Comment by Harmandodelavega** [comment]
Anecdotal but playing Eshin Imrik didn't get a single prince

**Comment by sm0kin** [comment]
Mostly a numbers game. The hef recruitment pool has 54 Archmages, 6 Princes and 6 Princesses at a time.
E.g. in my 200 turn Imrik campaign Eathaine fields 2 legendary lords, 3 princesses and 2 archmage armies.
